[package]
name = "dao"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio-native-tls"] }
serde_json = "1.0"