[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["mysql", "chrono"] }
chrono = "0.4.38"
serde = { version = "1.0", features = ["derive"] }


utils = { path = "../utils" }