[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
axum = "0.8.1"
axum-macros = "0.5.0"

service = { path = "../service" }
utils = { path = "../utils" }
domain = { path = "../domain" }